### ISSUE TITLE
Add/remove packages sample on home page

### ISSUE THREAD

**Issue by avaer** [webaverse/dashboard#10]
The home page uses XRPackages for doing all of the rendering. The intent is to showcase package composition.

The packages are all in separate Github repose -- the compiled `.wbn` versions are used during load.

The packages can be added/removed dynamically via the API. That is the API used to implement the [XPackage edit page](https://github.com/webaverse/xrpackage/blob/master/edit.js).

- https://github.com/webaverse/xrpackage/blob/f73ef696282fbe8a781d9716c3f75c9864809d6f/xrpackage.js#L561
- https://github.com/webaverse/xrpackage/blob/f73ef696282fbe8a781d9716c3f75c9864809d6f/xrpackage.js#L580

It would be good to have sample packages be selected/added/removed in this home page scene to showcase the functionality. For that we could use a sidebar on the right hand side of the render as we do on the XRPackage edit page.

**Comment by vyrnix9582046173** [comment]
outdated issue
