### ISSUE TITLE
Reduce payload size

### ISSUE THREAD

**Issue by avaer** [webaverse/dashboard#14]
Many of the packages on the site have unused files and models -- sometimes megabytes's worth.

We should probably go through each package (in its repository), delete extraneous files, and then rebuild and re-upload the packages to this site.

<img width="687" alt="extra" src="https://user-images.githubusercontent.com/6926057/84607551-eedea300-ae7b-11ea-8fac-4fe7507cd90a.png">

**Comment by shu8** [comment]
I've made PRs to delete all the unused files and reduce the package sizes for the packages used on webaverse.com (see https://github.com/webaverse/webaverse/blob/master/app.js). To summarise:

- `chest` -- https://github.com/avaer/chest/pull/1. 1330kB -> 661kB (unbaked)
- `grass` -- https://github.com/avaer/grass/pull/1. 1313kB -> 735kB (unbaked)
- `cloud` -- https://github.com/avaer/cloud/pull/1. 1316kB -> 729kB (unbaked)
- `multitree` -- https://github.com/avaer/multitree/pull/1. 4041kB -> 2860kB (unbaked)
- `ocean` -- https://github.com/avaer/ocean/pull/1. 1405kB -> 720kB (unbaked)
- `skybox` -- https://github.com/avaer/skybox/pull/1. 1440kB -> 637kB (unbaked)
- `sprites` -- https://github.com/avaer/sprite/pull/1. 1533kB -> 858kB (unbaked) 

Once these are reviewed/merged we can copy the `.wbn` files over the the `webaverse` repo at https://github.com/webaverse/webaverse/tree/master/augs.

Thanks to @yahengsu for making a plan on how to approach this issue and researching the packages needed to be updated!

---

Note all of these packages bundle a minified version of three.js with them, which is still 610kB in size, so this is the bulk of most of these packages. If/when Import Maps https://github.com/webaverse/xrpackage/issues/87 become a thing, it would really help to reduce loading times and download sizes for this!

**Comment by vyrnix9582046173** [comment]
outdated issue
