### ISSUE TITLE
Site sidebar seems clickable but isn't

### ISSUE THREAD

**Issue by avaer** [webaverse/dashboard#2]
Right site right sidebars currently feel like they should be clickable but users get confused that they are not.

![Screen Shot 2020-04-24 at 7 22 13 PM](https://user-images.githubusercontent.com/6926057/80264117-fe522480-8660-11ea-902b-0758eaff87cb.png)

**Comment by shu8** [comment]
With the new web design (with no sidebar anymore), I think this issue could be closed?

**Comment by avaer** [comment]
Yup thank you. We will still probably re-add the icons but that is a separate issue.
