### ISSUE TITLE
3d Scene elements don't load on iOS 

### ISSUE THREAD

**Issue by JaredMonkey** [webaverse/dashboard#8]
On iOS I'm seeing the background not load in
![image](https://user-images.githubusercontent.com/356520/84294021-6cfa1d00-aafd-11ea-8586-b42ec2bd8364.png)

A progressive enhancement approach, when the scene doesn't load could be nice for fallback.

**Comment by avaer** [comment]
This might be an `xrpackage` issue -- would be good to get stack traces on this. I suspect there would be one.

I believe `webgl2` is currently required/assumed but that doesn't necessarily need to be the case.

**Comment by vyrnix9582046173** [comment]
outdated issue
